services:
    nginx:
        image: curse89/documentation-site:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .docker/prod/nginx.conf:/etc/nginx/conf.d/default.conf
            - /etc/nginx/ssl:/etc/nginx/ssl